#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_FILE="${SCRIPT_DIR}/config"
TMPDIR_CLEANUP=""

die() {
    echo "ERROR: $*" >&2
    exit 1
}

info() {
    echo "[INFO] $*"
}

warn() {
    echo "[WARN] $*" >&2
}

require_root() {
    [[ "${EUID}" -eq 0 ]] || die "Please run as root: sudo bash $0"
}

load_config() {
    if [[ ! -f "${CONFIG_FILE}" ]]; then
        cat >&2 <<'EOF'
Missing ./config.

Please run:
  cp config.example config
  nano config
EOF
        exit 1
    fi

    # shellcheck source=/dev/null
    source "${CONFIG_FILE}"

    : "${OPENRESTY_CONF:=/usr/local/openresty/nginx/conf}"
}

backup_file() {
    local file="$1"
    [[ -f "${file}" ]] || return 0
    local stamp
    stamp="$(date +%Y%m%d-%H%M%S)"
    cp -a "${file}" "${file}.bak.${stamp}"
}

fetch_cloudflare_ips() {
    local tmpdir="$1"
    curl -fsSL https://www.cloudflare.com/ips-v4 -o "${tmpdir}/ips-v4"
    curl -fsSL https://www.cloudflare.com/ips-v6 -o "${tmpdir}/ips-v6"

    [[ -s "${tmpdir}/ips-v4" ]] || die "Cloudflare IPv4 list is empty."
    [[ -s "${tmpdir}/ips-v6" ]] || die "Cloudflare IPv6 list is empty."
}

write_realip_snippet() {
    local tmpdir="$1"
    local snippet="${OPENRESTY_CONF}/snippets/cloudflare-realip.conf"
    local tmp_snippet="${tmpdir}/cloudflare-realip.conf"
    local set_real_ip_file="${tmpdir}/set-real-ip.conf"

    mkdir -p "${OPENRESTY_CONF}/snippets"

    awk 'NF { print "set_real_ip_from " $0 ";" }' "${tmpdir}/ips-v4" "${tmpdir}/ips-v6" > "${set_real_ip_file}"

    if [[ -f "${SCRIPT_DIR}/templates/cloudflare-realip.conf.tpl" ]]; then
        awk -v repl_file="${set_real_ip_file}" '
            {
                if ($0 == "{{SET_REAL_IP_FROM}}") {
                    while ((getline line < repl_file) > 0) print line
                    close(repl_file)
                } else {
                    print
                }
            }
        ' "${SCRIPT_DIR}/templates/cloudflare-realip.conf.tpl" > "${tmp_snippet}"
    else
        {
            echo "# Generated by update-cf-ips.sh."
            echo "real_ip_header CF-Connecting-IP;"
            echo "real_ip_recursive on;"
            cat "${set_real_ip_file}"
        } > "${tmp_snippet}"
    fi

    if [[ -f "${snippet}" ]] && cmp -s "${tmp_snippet}" "${snippet}"; then
        info "Cloudflare real IP snippet is already up to date."
    else
        backup_file "${snippet}"
        install -m 0644 "${tmp_snippet}" "${snippet}"
        info "Updated ${snippet}."
    fi
}

ufw_is_active() {
    ufw status | grep -q '^Status: active'
}

managed_ufw_rule_numbers() {
    local pattern="$1"
    ufw status numbered | awk -v pattern="${pattern}" '
        $0 ~ pattern && match($0, /^\[[[:space:]]*[0-9]+\]/) {
            rule = substr($0, RSTART, RLENGTH)
            gsub(/[^0-9]/, "", rule)
            print rule
        }
    ' | sort -rn
}

clear_managed_cf_ufw_rules() {
    mapfile -t rule_numbers < <(managed_ufw_rule_numbers '(restyfleet|openresty-manager)-cloudflare')
    local rule
    for rule in "${rule_numbers[@]:-}"; do
        [[ -n "${rule}" ]] && ufw --force delete "${rule}" >/dev/null
    done
}

update_ufw_rules() {
    local tmpdir="$1"
    local ip

    if ! command -v ufw >/dev/null 2>&1; then
        warn "UFW is not installed; only OpenResty real IP snippet was updated."
        return
    fi

    if ! ufw_is_active; then
        warn "UFW is inactive; not adding firewall rules and not enabling UFW."
        return
    fi

    clear_managed_cf_ufw_rules

    while IFS= read -r ip; do
        [[ -z "${ip}" ]] && continue
        ufw allow from "${ip}" to any port 80 proto tcp comment "restyfleet-cloudflare"
        ufw allow from "${ip}" to any port 443 proto tcp comment "restyfleet-cloudflare"
    done < <(cat "${tmpdir}/ips-v4" "${tmpdir}/ips-v6")
}

reload_openresty_if_available() {
    if ! command -v openresty >/dev/null 2>&1; then
        warn "openresty command not found; skipping config test and reload."
        return
    fi

    openresty -t

    if command -v systemctl >/dev/null 2>&1 && systemctl is-active --quiet openresty; then
        systemctl reload openresty
    else
        warn "OpenResty service is not active; config tested but service was not reloaded."
    fi
}

main() {
    require_root
    load_config

    local ipv4_count ipv6_count
    TMPDIR_CLEANUP="$(mktemp -d)"
    trap '[[ -n "${TMPDIR_CLEANUP:-}" ]] && rm -rf "${TMPDIR_CLEANUP}"' EXIT

    fetch_cloudflare_ips "${TMPDIR_CLEANUP}"
    ipv4_count="$(awk 'NF { count++ } END { print count + 0 }' "${TMPDIR_CLEANUP}/ips-v4")"
    ipv6_count="$(awk 'NF { count++ } END { print count + 0 }' "${TMPDIR_CLEANUP}/ips-v6")"

    write_realip_snippet "${TMPDIR_CLEANUP}"
    update_ufw_rules "${TMPDIR_CLEANUP}"
    reload_openresty_if_available

    echo "Cloudflare IP update completed: IPv4=${ipv4_count}, IPv6=${ipv6_count}."
}

main "$@"
